| Privacy Threat Category | Threat Description  | MAP Persona | Privacy Design Strategies for  Mitigation |
|---|---|---|---|
| Kick-off questions | Does the   application code contain personal information?   | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
|  | Do any   databases used by the application contain personal information? If the   application has personal information, has it been de-deidentified?  | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
|   | Do any   application logs contain personal information?   | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
| Special categories of PI | Biometric   data: Does the application collect biometric data?  General guidelines: Biometric data   (fingerprints, retina scans, etc.) require explicit notice and written   consent from customers before collection. Such data can also not be sent to   third-parties, monetized, or retained without consent.  | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
|  | Children   data: Does the application collect data from youth   under 16? General guidelines: Data collected from children   require explicit notice and written consent from parents/guardians (for users   under 13 years) or children (for users between 13-16 years).  Such data can also not be sent to   third-parties, monetized, or retained without consent. Privacy settings   should be easy to understand for children. If the child is being tracked by   an adult through the application, the child should be notified (for example,   a green LED light can indicate that a camera is switched on). | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
|  | CPNI: Does the application contain CPNI data?  General guidelines: The use of CPNI data is   limited to specific purposes. It cannot be used for marketing that a customer   has not opted into. | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
|  | Voice and   Video: Does the application collect voice or video   data?      General guidelines: Voice data cannot be used   for advertisement purposes, even if collected by or for a third-party   partner. Organization must have an individual’s prior, written permission before   collecting or recording any audiovisual or other sensor data from within   their dwelling. For both video and voice data, specific consent obligations  must be met.  | X | Existence of PI is not a threat.   Team must ensure that these are properly handled when they exist, and review is done for special categories of PI.  |
| Accountability and auditing | Are changes to application code attributed and logged?       This code can be present on GitHub, AWS,   Databricks, or any other platform. | P3 | Privacy Logging and Reporting |
|  | Are changes to   application components, like databases, servers, etc., attributed and   logged?  | P3 | Privacy Logging and Reporting |
|  | Is access to any   personal information across your application logged? | P3 | Privacy Logging and Reporting |
|  | Is there a way   to download data out of the application? If yes, do we have logs to track the   same?  | P9 | Privacy Logging and Reporting |
|   | Can we track who is viewing any   personal information on your application's interface?  | P14 | Privacy Logging and Reporting |
| Data quality and integrity | Does your application combine   customer data across different platforms (mobile, television, laptop, etc.)? | P10 | Data Separation |
|  | Do you check the   quality of personal data used by your application (for errors, mistakes,   incomplete information, etc.)? | P6 | Transparency and   Disclosure,     Consumer Control,      Data Separation |
|   | Does your   application make inferences about a customer that can result in a negative   impact, such as denial of service? | P6 | Transparency and   Disclosure      Consumer Control      Data Separation |
| Use limitation | Does your application collect   location data or other proxies for location that can be linked to a   user/group in any way?  | P11 | Data De-identification |
|   | Do you collect   customer's behavioral data (like websites they visit, number of clicks,   likes, engagement, etc.) that can reveal user patterns? | P10 | Data Separation |
| Data minimization | Is your application collecting   only the minimum data necessary for the app to function?  If not, have you documented the reason for   collecting additional information? Is data disposal done for data that is no   longer required by the application? | P12 | Data Reduction |
|  | If the   application is customer-facing, is the information that a customer can view   provided on a need to know basis? | P14 | Data Separation,     Privacy Logging and Reporting |
|  | Is the   information that a developer/owner of the application can view provided on a   need to know basis? Is access regularly updated if change in role occurs? | P9 | Privacy Logging and   Reporting,      (Encryption),     (Access Control) |
|   | Does any component in your   application contain links? Do these links redirect to any personal   information without requiring authentication?  | P7 | Data De-identification      (Access Control) |
| Transparency | Can a user request a copy of   their data for download? Are organizational retention policies followed for storing   user data? | P8 | Consumer Control |
|  | Do you provide markers/indicators when collecting user data?         These can be in the form of LED lights, cookie   banners, pop-ups, etc. that is relevant for your application.  | P17 | Transparency and   Disclosure      Consumer Control |
|   | Does the output of your application present one users   information to another without notifying (even in an aggregate or   de-identified form)?       For example, a notification may be two beeps or   a different beep for an event when their data is being shared. Note that organization cannot disclose   consumers' electronic communications (e.g., phone calls, email, Internet   transmissions) to anyone other than the intended recipient. | P16 | Data De-identification      (Access Control) |
| Security (basic PI safeguards) | Are personal   information records backed up in case of accidental deletion?   | P3 | Privacy Logging and   Reporting      (Backup) |
|  | Can the   customer add a second factor to allow for stronger authentication on their   account?      Internal systems that allow access to personal   information must have multi-factor authentication in place by default to meet   this condition.  | P14 | Data Separation      Privacy Logging and Reporting |
|  | Does you   application have any defenses to prevent brute force attacks to retrieve   personal information?       For example, you may lock a customers' account   after three incorrect attempts. | P14 | Data Separation      Privacy Logging and Reporting |
|  | Does the   customer need to provide additional authentication to change sensitive data on the   account? | P14 | Data Separation      Privacy Logging and Reporting |
|  | Does the   customer need to provide additional authentication to access sensitive data on the   account? | P14 | Data Separation      Privacy Logging and Reporting |
|  | Does you   application notify the customer if there is any unusual behavior (like after   a certain number of incorrect logins, logging in from an unusual   location,etc.)?       For example, the customer may receive a text   message when three or more unsuccessful login attempts are made. | P14 | Data Separation      Privacy Logging and Reporting |
|  | Would an unauthorized employee be able to access identifiable   data of other users through your application?       Unauthorized employee could be anyone who does   not a have a job-related purpose for viewing user data.  | P2 | (Access Control) |
|  | Is personal   information stored in plaintext in any part of your application? Do you   employ the recommended encryption approaches throughout your application   compliant with organization policy?       This includes FIPS standards for both encryption   at rest and in transit. Datastores containing Social Security Numbers must   meet or exceed organization's encryption standards.  | P9 | (Encryption) |
|  | Do you share the data over a   secure channel? If yes, is there authentication in place for who can access   this information?  | P4 | Data Reduction |
|   | If the   application is customer-facing, can it be authenticated using information   that is publicly available?       For example, a homeowner's home address   information in USA is often publicly available on a county's website. | P13 | Data Separation |
| Purpose specification | Is personal   information provided used for a secondary purpose by the application? Have   customers consented to this secondary usage? Can they opt-out of secondary   usage of their data? If a customer has opted out, do you ensure that such   customer data is filtered out from secondary usage?       For example, data might have been collected to   provide services, but is now also used to provide ads.  | P15 | Data Reduction      Transparency and Disclosure |
|  | Would the data from your   application be otherwise made available publicly? | P13 | Data Separation |
|   | Do   individuals who have provided personal information know about its usage by   this application?      Applications which process user data should   provide information to users about this usage and purpose.  | P17 | Transparency and Disclosure |
| Individual participation | Is there a   way for individuals to opt out of the collection/processing of their   data?      This requirement is fully satisfied only if the   language to opt out must be easy to understand and the opt out request is   fully implemented by restricting processing of the specified data. Opt out   should not be harder than opt in. If this is out of scope for your   application, please indicate the dataset and the team responsible in the   comments.  | P17 | Consumer Control |
|  | Can the   application potentially collect information from users who are not the   primary customer without consent?       For example, a video app could collect viewing   history from multiple users using the same television.  | P17 | Consumer Control |
|  | If there is   a personal data deletion or modification request, would it be possible to   implement it across the application?       For example, when there is deletion request, the   application can automatically remove records from all databases, servers, and   other containers, including third party transfers. There should be clear   description of how to request a deletion or modification. | P8 | Consumer Control |
|   | Does your   application automatically pull information from the user or their device   without consent? is it possible that this automatic collection may include   data that is not needed for the functionality of your application?       Note that for "full informed consent",   it should be (a) clearly indicated by a user by performing an action, like   checking a box or clicking a button, (b) have specific details on what is   being collected and who will be receiving the information, and (b) be freely   given without coercion.  | P15 | Data Reduction      Transparency and Disclosure |
| Third-party sharing | If the   application sends data to third parties, do you have a data loss prevention   (DLP) control mechanism in place?       A DLP mechanism, like an email filter for   example, prevents unexpected and uncontrolled loss of internal data.  | P9 | Privacy Logging and Reporting |
|  | If the   application sends data to third parties, do customers know about this in   their privacy policy? Have they consented to this extended use?      To satisfy "customer knowledge",   clarify the (a) type of third-party (which industry category), (b) clear   purpose of transfer, and (c) frequency of transfer, (d) all personal   information categories transferred either to or from a third-party, and (e)   general source of the personal information obtained.      Privacy Policy must be presented as a conspicuous link. For additional   details on how to implement, please refer to 2.2 (18) of the Global Privacy   Tool. | P5 | Transparency and   Disclosure      Consumer Control |
|  | Can customers limit their data   from being shared by vendors to other applications?        | P5 | Transparency and   Disclosure      Consumer Control |
|  | Are   customers able to access/modify their data that is sent to vendors?       There should be clear description of how to   request a deletion or modification.  | P5 | Transparency and   Disclosure      Consumer Control |
|  | Does your   application share data with third parties? Have they been approved through a   third party security assessment? Have they gone through the de-identification   process? If not, do they have measures in place to handle PI according to   stipulated retention policies?       Customers cannot be refused service by organization if they restrict names and addresses from being used by third-parties for   mailing list subscriptions.  | P5 | Transparency and   Disclosure      Consumer Control |
|  | Is all of   the shared data required for the third party to provide the required   functionality? If not, do you remove unnecessary data elements before sending   them to the third-party?       Unnecessary data can also include user data who   are no longer customers. Such data should not be collected.  | P5 | Transparency and   Disclosure      Consumer Control |
|   | Does this application use   personal data from third parties? Do owners of the personal data (all users,   including employees) know about the source of the data? Do you validate the   correctness of the data received from the third party?  | P5 | Transparency and   Disclosure      Consumer Control |
